# Generated by Django 6.0.6 on 2026-06-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_bank_payment_card_last4_payment_card_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='upa_vpa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_intent_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_qr_code',
            field=models.TextField(blank=True),
        ),
    ]
