# Generated by Django 6.0.6 on 2026-06-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_upa_vpa_payment_upi_intent_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='upa_vpa',
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_vpa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
