# Generated by Django 6.0.6 on 2026-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_upa_vpa_payment_upi_vpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('gateway_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='netbanking_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_txn_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
