# Generated by Django 6.0.6 on 2026-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_bank_payment_bank_code_payment_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='netbanking_url',
            field=models.TextField(blank=True),
        ),
    ]
