# Generated by Django 6.0.6 on 2026-06-09 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_netbanking_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.CharField(blank=True, max_length=100)),
                ('gateway_refund_id', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'db_table': 'refunds',
                'indexes': [models.Index(fields=['payment', 'status'], name='refunds_payment_908281_idx'), models.Index(fields=['created_at'], name='refunds_created_7e4196_idx')],
            },
        ),
    ]
