# Generated by Django 6.0.6 on 2026-06-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='in_settlement',
            field=models.BooleanField(default=False),
        ),
    ]
