# Generated by Django 6.0.6 on 2026-06-11 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_bank_verified_merchant_kyc_rejection_reason_and_more'),
        ('payments', '0008_add_in_settlement_to_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=32, unique=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('paid', 'Paid'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='merchants.merchant')),
            ],
            options={
                'db_table': 'payment_links',
                'indexes': [models.Index(fields=['merchant', 'status'], name='payment_lin_merchan_1fc3f3_idx'), models.Index(fields=['slug'], name='payment_lin_slug_24947e_idx')],
            },
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('virtual_upi_id', models.CharField(max_length=100, unique=True)),
                ('virtual_account_number', models.CharField(max_length=20, unique=True)),
                ('virtual_ifsc', models.CharField(default='PAYZ0000001', max_length=11)),
                ('amount_expected', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('close_by', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_accounts', to='merchants.merchant')),
            ],
            options={
                'db_table': 'virtual_accounts',
                'indexes': [models.Index(fields=['merchant', 'status'], name='virtual_acc_merchan_dd6453_idx'), models.Index(fields=['virtual_upi_id'], name='virtual_acc_virtual_cdaeec_idx'), models.Index(fields=['virtual_account_number'], name='virtual_acc_virtual_b4563e_idx')],
            },
        ),
    ]
