# Generated by Django 6.0.6 on 2026-06-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_webhook_1b7a43_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_event_t_1d3d5d_idx',
        ),
        migrations.RenameField(
            model_name='webhookevent',
            old_name='webhook',
            new_name='endpoint',
        ),
        migrations.RenameIndex(
            model_name='webhookendpoint',
            new_name='webhook_end_merchan_f878b8_idx',
            old_name='webhooks_merchan_ff958f_idx',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='secret_hash',
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='secret',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='response_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['endpoint', 'event_type'], name='webhook_eve_endpoin_73e31b_idx'),
        ),
        migrations.AlterModelTable(
            name='webhookendpoint',
            table='webhook_endpoints',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='response_status_code',
        ),
    ]
