# Generated by Django 6.0.6 on 2026-06-06 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('fee_rate', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
                ('is_live', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'merchants',
                'indexes': [models.Index(fields=['email'], name='merchants_email_fc58cd_idx'), models.Index(fields=['kyc_status'], name='merchants_kyc_sta_673bd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_prefix', models.CharField(max_length=20)),
                ('key_hash', models.CharField(max_length=128)),
                ('is_live', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='merchants.merchant')),
            ],
            options={
                'db_table': 'api_keys',
                'indexes': [models.Index(fields=['key_prefix'], name='api_keys_key_pre_9c2634_idx'), models.Index(fields=['merchant', 'is_active'], name='api_keys_merchan_6f6dc2_idx')],
            },
        ),
    ]
