# Generated by Django 6.0.6 on 2026-06-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(max_length=30),
        ),
    ]
