# Generated by Django 6.0.6 on 2026-06-10 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_apikey_key_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='bank_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='kyc_reviewed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('business_reg', 'Business Registration'), ('cancelled_cheque', 'Cancelled Cheque'), ('bank_statement', 'Bank Statement'), ('gst_certificate', 'GST Certificate')], max_length=30)),
                ('file_key', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='merchants.merchant')),
            ],
            options={
                'db_table': 'kyc_documents',
                'indexes': [models.Index(fields=['merchant', 'document_type'], name='kyc_documen_merchan_6dd134_idx'), models.Index(fields=['status'], name='kyc_documen_status_355905_idx')],
                'unique_together': {('merchant', 'document_type')},
            },
        ),
    ]
