# Generated by Django 6.0.6 on 2026-06-10 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0008_add_in_settlement_to_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('block', 'Block'), ('flag', 'Flag for Review'), ('step_up', 'Step-up Auth')], max_length=20)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('threshold', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fraud_rules',
            },
        ),
        migrations.CreateModel(
            name='FraudSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_triggered', models.CharField(max_length=100)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('action_taken', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_signals', to='payments.payment')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='fraud.fraudrule')),
            ],
            options={
                'db_table': 'fraud_signals',
                'indexes': [models.Index(fields=['payment', 'status'], name='fraud_signa_payment_5e953b_idx'), models.Index(fields=['status', 'created_at'], name='fraud_signa_status_37e1d5_idx')],
            },
        ),
    ]
