# Generated by Django 6.0.6 on 2026-06-10 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0002_alter_apikey_key_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('mode', models.CharField(choices=[('NEFT', 'NEFT'), ('IMPS', 'IMPS'), ('UPI', 'UPI')], default='IMPS', max_length=10)),
                ('purpose', models.CharField(choices=[('payout', 'Payout'), ('refund', 'Refund'), ('cashback', 'Cashback'), ('salary', 'Salary'), ('vendor', 'Vendor Payment'), ('other', 'Other')], default='payout', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='queued', max_length=20)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('utr_number', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('reference_id', models.CharField(blank=True, max_length=255)),
                ('batch_id', models.CharField(blank=True, max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='merchants.merchant')),
            ],
            options={
                'db_table': 'payouts',
                'indexes': [models.Index(fields=['merchant', 'status'], name='payouts_merchan_44832a_idx'), models.Index(fields=['batch_id'], name='payouts_batch_i_149576_idx'), models.Index(fields=['created_at'], name='payouts_created_1441ca_idx')],
            },
        ),
    ]
