apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payzap-ingress
  namespace: payzap
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1s"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.payzap.com
        - dashboard.payzap.com
      secretName: payzap-tls
  rules:
    - host: api.payzap.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payzap-api
                port:
                  number: 80
    - host: dashboard.payzap.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payzap-api
                port:
                  number: 80