apiVersion: v1
kind: Service
metadata:
  name: payzap-api
  namespace: payzap
spec:
  selector:
    app: payzap-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP