# Generated by Django 6.0.6 on 2026-06-06 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('fees', models.PositiveIntegerField(default=0)),
                ('tax', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('utr_number', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11)),
                ('settlement_from', models.DateTimeField()),
                ('settlement_to', models.DateTimeField()),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='merchants.merchant')),
            ],
            options={
                'db_table': 'settlements',
                'indexes': [models.Index(fields=['merchant', 'status'], name='settlements_merchan_1f45d0_idx'), models.Index(fields=['status', 'created_at'], name='settlements_status_1a84dc_idx')],
            },
        ),
    ]
